### ISSUE TITLE
error loading script

### ISSUE THREAD

**Issue by arbuzai** [thundaga/SD-webui-txt2img-script#1]
hello, i tired using script on my pc and on colab but i get this error on start up

Error loading script: process_png_metadata.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/process_png_metadata.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by thundaga** [comment]
Currently line 8 is supposed to import information from the "processing" file in the modules folder.
Does your local webui have the most recent update?
Is the webui's processing file inside the modules folder?

**Comment by arbuzai** [comment]
I'm sorry, the script file got messed up somehow. I redownloaded it, and it works now.
Thank you for making this script, it is very useful <3
Sorry for the inconvenience ><
