### ISSUE TITLE
Not working with new WebUI Forge 

### ISSUE THREAD

**Issue by TondaPrdka** [thundaga/SD-webui-txt2img-script#31]
Exelent script, sadly after update of WebUI Forge (Version: f2.0.1v1.10.1-previous-619-g92d6bbaa pytorch version: 2.3.1), the script menu no longer pops up after selecting script. Forge version f0.0.17v1.8.0rc-latest-276-g29be1da7], torch: 2.1.2 works fine.

![image](https://github.com/user-attachments/assets/f3d5ddba-b9f2-400a-b08d-5493591693f0)

If it helps:

> ''*** Error executing callback app_started_callback for D:\webui_forge_cu121_torch231\webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch231\webui\modules\script_callbacks.py", line 256, in app_started_callback
        c.callback(demo, app)
      File "D:\webui_forge_cu121_torch231\webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 793, in on_app_started
        task_runner = get_instance(block)
      File "D:\webui_forge_cu121_torch231\webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 628, in get_instance
        TaskRunner(UiControlNetUnit)
      File "D:\webui_forge_cu121_torch231\webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 75, in __init__
        self.__api = Api(FastAPI(), queue_lock)
      File "D:\webui_forge_cu121_torch231\webui\modules\api\api.py", line 263, in __init__
        self.default_script_arg_txt2img = self.init_default_script_args(txt2img_script_runner)
      File "D:\webui_forge_cu121_torch231\webui\modules\api\api.py", line 330, in init_default_script_args
        if script.ui(script.is_img2img):
      File "D:\webui_forge_cu121_torch231\webui\scripts\process_png_metadata.py", line 148, in ui
        with gr.Row().style(equal_height=False, variant='compact'):
    AttributeError: 'Row' object has no attribute 'style'`

**Comment by Nekuro25** [comment]
Got a fix, but no permission, repo also lacked scripts folder so import via ui didnt work

156 or so: with gr.Row():

**Comment by OPCOXE** [comment]
Thanks to "help" but nobody answered because the question was already answered...
The issue here is reading it seems ->https://github.com/thundaga/SD-webui-txt2img-script/issues/25<-
PS: I might be mean but making anyone lose time because you don't want to lose yours doesn't make people want to help...

**Comment by Nekuro25** [comment]
So SD is still on older libs, hmm, do you want to have 2 scripts, one for a1111 and one for forge? or simply stay a1111 ? made PR for some changes for forge...
